---
kind: pipeline
type: kubernetes
name: drone

platform:
  arch: amd64
  os: linux

steps:
  - name: Build
    image: golang:1.13.0
    commands:
      - go test
      - go build -o main
    volumes:
      - name: artifacts
        path: /go
    environment:
      GOARCH: amd64
      GOOS: linux

  - name: release
    image: node:latest
    settings:
      debug: true
    commands:
      - docker login -u $USERNAME -p $PASSWORD
      - docker build -t hello-world .
      - docker push hello-world
    volumes:
      - name: artifacts
        path: /go
    when:
      event:
        - pull_request
        - push
    environment:
      PASSWORD:
        from_secret: password
      USERNAME:
        from_secret: username

volumes:
  - name: cache
    temp: {}